---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 5
  selector:
    matchLabels:
      app: url-shortener
  template:
    metadata:
      labels:
        app: url-shortener
      annotations:
        sidecar.istio.io/proxyCPU: "100m"
        sidecar.istio.io/proxyCPULimit: "1000m"
        sidecar.istio.io/proxyMemory: "1Gi"
        sidecar.istio.io/proxyMemoryLimit: "1536Mi"
    spec:
      automountServiceAccountToken: false
      containers:
        - name: url-shortener
          image: ghcr.io/prefeitura-rio/url_shortener:stable
          envFrom:
            - secretRef:
                name: url-shortener-secrets
          resources:
            requests:
              ephemeral-storage: 100Mi
              cpu: 1000m
              memory: 1Gi
            limits:
              cpu: 2000m
              memory: 2Gi
          readinessProbe:
            httpGet:
              path: /api/health
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
            successThreshold: 1
          livenessProbe:
            httpGet:
              path: /api/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
      restartPolicy: Always
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: url-shortener-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: url-shortener
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: url-shortener-scaled-object
  annotations:
    autoscaling.keda.sh/trigger-authentication: "default"
spec:
  scaleTargetRef:
    name: url-shortener
  minReplicaCount: 2
  maxReplicaCount: 10
  cooldownPeriod: 30
  pollingInterval: 10
  fallback:
    failureThreshold: 3
    replicas: 2
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleUp:
          stabilizationWindowSeconds: 60
          policies:
          - type: Percent
            value: 100
            periodSeconds: 15
          - type: Pods
            value: 2
            periodSeconds: 15
          selectPolicy: Max
        scaleDown:
          stabilizationWindowSeconds: 300
          policies:
          - type: Percent
            value: 10
            periodSeconds: 60
          - type: Pods
            value: 1
            periodSeconds: 60
          selectPolicy: Max
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://prometheus.istio-system.svc.cluster.local:9090
        metricName: http_requests_total
        threshold: "2000"
        query: sum(rate(istio_requests_total{destination_workload="url-shortener"}[30s]))
        activationThreshold: "1500"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: url-shortener
  name: url-shortener
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 8080
  selector:
    app: url-shortener